### ISSUE TITLE
update 4.5

### ISSUE THREAD

**Issue by hlugt** [biarms/pgadmin4#7]
Hi, this is not an issue but more a remark. Updated your image locally to alpine 3.9 and pgadmin4.5. Had only to add the packages  libffi libffi-dev for that. Tried pgadmin 4.6 but when running on arm it gives an error I have had no time to look at yet.
Thx for your multiarch dockerfile!

**Comment by biarms** [comment]
Many thanks for this comment. Unfortunately, I did a configuration mistake on github and I was never notify about it :(.
FYI, I have publish an upgrade to 4.12, so I close this comment.
